#
# test-kitchen using kitchen-dokken
#
# to use this instead of Vagrant, use:
#
#   $ KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify
#
driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: 12.19.36

transport:
  name: dokken

provisioner:
  name: dokken

platforms:
# comment this out, if Debian 7 is not needed
- name: debian-7
  driver:
    image: dokken/debian-7
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN echo "Acquire::Check-Valid-Until \"false\";" > /etc/apt/apt.conf.d/99-chef-override
      - RUN echo "APT::Get::force-yes \"true\";" >> /etc/apt/apt.conf.d/99-chef-override
      - RUN sed -i 's#http://deb.debian.org/debian#http://archive.debian.org/debian/#; s#http://security.debian.org/debian-security#http://archive.debian.org/debian-security/#; /wheezy-updates/d' /etc/apt/sources.list
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools cron -y

# suites are taken from .kitchen.yml usually
# suites:
