#
# test-kitchen using kitchen-dokken
#
# to use this instead of Vagrant, use:
#
#   $ KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify
#
driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken

platforms:
# comment this out, if Debian 7 is not needed
- name: debian-7
  driver:
    image: dokken/debian-7
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools cron -y

# suites are taken from .kitchen.yml usually
# suites:
